name: Upload npm protos to google artifact registry
description: Uploads generated protos to google artifact registry
inputs:
  credentials-json:
    description: Google credentials json
    required: true
  project-id:
    description: Google cloud project id
    required: true
  package-name:
    description: NPM package name
    required: true
  version:
    description: Version to publish
    required: false
    default: ${{ .github.event.release.tag_name }}
  scope:
    description: Artifact registry scope - i.e. @mycompany
    required: true
  repository:
    description: Artifact registry repository name
    required: false
    default: npm
  location:
    description: Artifact registry location
    required: false
    default: us-central1
  proto-directory:
    description: Location of the generated protos
    required: false
    default: build/nodejs
runs:
  using: composite
  steps:
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.credentials-json }}
    - uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ inputs.project-id }}
    - name: Publish artifacts using ephermeral npm project
      shell: bash
      run: |
        mkdir ephemeralnpm
        cd ephemeralnpm
        npm init -y
        json="$(jq --arg version "${{ inputs.version }}" '.name = "${{ inputs.scope }}/${{ inputs.package-name }}" | .version = $version' package.json)"
        echo "${json}" > package.json
        echo "$(gcloud artifacts print-settings npm --scope=${{ inputs.scope }} --repository ${{ inputs.repository }} --location ${{ inputs.location }})" | sed 1,2d > .npmrc
        cp -r ../${{ inputs.proto-directory }}/* .
        npx google-artifactregistry-auth -y
        npm publish
        
